name: ubuntu_desktop_installation_slides
publish_to: 'none'

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-alpha.6
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.0
  handy_window: ^0.3.1
  intl: ^0.17.0
  provider: ^6.0.5
  window_manager: ^0.3.1
  yaru: ^0.5.5
  yaru_colors: ^0.1.6
  yaru_icons: ^1.0.3
  yaru_widgets: ^2.1.1

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/installation_slides/
    - assets/installation_slides/icons/
    - assets/installation_slides/icons/dark/
    - assets/installation_slides/icons/light/
    - assets/installation_slides/screenshots/
    - assets/installation_slides/screenshots/2.0x/
    - assets/installation_slides/screenshots/dark/
    - assets/installation_slides/screenshots/dark/2.0x/
    - assets/installation_slides/screenshots/light/
    - assets/installation_slides/screenshots/light/2.0x/
